//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlavourFusion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlavourFusionEntities2 : DbContext
    {
        public FlavourFusionEntities2()
            : base("name=FlavourFusionEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
        public virtual DbSet<Tbl_Membership_Plans> Tbl_Membership_Plans { get; set; }
        public virtual DbSet<Tbl_Subscriptions> Tbl_Subscriptions { get; set; }
        public virtual DbSet<Tbl_Users> Tbl_Users { get; set; }
        public virtual DbSet<Tbl_Recipe> Tbl_Recipe { get; set; }
        public virtual DbSet<Tbl_Recipe_Category> Tbl_Recipe_Category { get; set; }
    }
}
