//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Web.Mvc;
namespace FlavourFusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Submissions
    {
        public int Submission_Id { get; set; }
        public int ContestId { get; set; }
        public int UserId { get; set; }
        public int Recipe_Category { get; set; }
        public string RecipeName { get; set; }
        public string RecipeDescription { get; set; }
        public string Recipe_image { get; set; }
        public Nullable<int> Recipe_ingredients { get; set; }
        public string Recipe_tags { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public Nullable<bool> WinnerStatus { get; set; }
        [AllowHtml]
        public string recipe_direction { get; set; }
        [AllowHtml]
        public string recipe_tutorial_video { get; set; }
    
        public virtual Tbl_Contests Tbl_Contests { get; set; }
        public virtual Tbl_Recipe_Category Tbl_Recipe_Category { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
