//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlavourFusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Subscriptions
    {
        public int subscription_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> plan_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
    
        public virtual Tbl_Membership_Plans Tbl_Membership_Plans { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
