//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlavourFusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Recipe
    {
        public int rec_id { get; set; }
        public string rec_name { get; set; }
        public string rec_desc { get; set; }
        public string rec_img { get; set; }
        public Nullable<int> cat_id_fk { get; set; }
    
        public virtual Tbl_Category Tbl_Category { get; set; }
    }
}
