using System.Web.Mvc;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlavourFusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Recipe()
        {
            this.Tbl_Comments = new HashSet<Tbl_Comments>();
        }
    
        public int recipe_id { get; set; }
        public string recipe_name { get; set; }
        public string recipe_description { get; set; }
        public string recipe_image { get; set; }
        public Nullable<int> FK_Category_Recipe { get; set; }
        public string recipe_ingredients { get; set; }
        public Nullable<int> recipe_duration { get; set; }
        public Nullable<int> recipe_serving_people { get; set; }
        public string recipe_tags { get; set; }
        public Nullable<System.DateTime> recipe_publish_date { get; set; }
        [AllowHtml]
        public string recipe_direction { get; set; }
        [AllowHtml]
        public string recipe_tutorial_video { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Comments> Tbl_Comments { get; set; }
        public virtual Tbl_Recipe_Category Tbl_Recipe_Category { get; set; }
    }
}
