//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlavourFusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Recipe_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Recipe_Category()
        {
            this.Tbl_Recipe = new HashSet<Tbl_Recipe>();
        }
    
        public int category_id { get; set; }
        public string category_name { get; set; }
        public string category_image { get; set; }
        public int category_status { get; set; }
        public Nullable<int> FK_Admin_Category { get; set; }
    
        public virtual Tbl_Admin Tbl_Admin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Recipe> Tbl_Recipe { get; set; }
    }
}
