//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlavourFusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Announcement
    {
        public int Annoucement_id { get; set; }
        public string Annoucement_Text { get; set; }
        public string Annoucement_Description { get; set; }
        public Nullable<System.DateTime> Annoucement_Date { get; set; }
    }
}
