//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlavourFusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        public int us_id { get; set; }
        public string us_name { get; set; }
        public string us_email { get; set; }
        public string us_password { get; set; }
        public string us_img { get; set; }
        public string us_phone { get; set; }
        public Nullable<int> mem_id_fk { get; set; }
    
        public virtual Tbl_Membership Tbl_Membership { get; set; }
    }
}
