//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlavourFusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Feedback
    {
        public int feedback_id { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public Nullable<System.DateTime> user_submission_date { get; set; }
        public string user_message { get; set; }
    }
}
