//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlavourFusion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Comments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Comments()
        {
            this.Tbl_Replies = new HashSet<Tbl_Replies>();
        }
    
        public int comment_id { get; set; }
        public int recipe_id { get; set; }
        public int user_id { get; set; }
        public string comment_text { get; set; }
        public System.DateTime comment_date { get; set; }
    
        public virtual Tbl_Recipe Tbl_Recipe { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Replies> Tbl_Replies { get; set; }
    }
}
